package is04v1_3

// Describes a JSON based Flow
type FlowJSONData struct {
	FlowCore
	Format    FormatURI `json:"format"`               // Format of the data coming from the Flow as a URN
	MediaType string    `json:"media_type"`           // Subclassification of the format, using IANA assigned media types where available, or other values defined in the NMOS Parameter Registers
	EventType string    `json:"event_type,omitempty"` // Event type generated by this Flow, if applicable
}
