package is04v1_3

// Describes a data Source
type SourceData struct {
	SourceCore
	Format    string `json:"format"`     // Format of the data coming from the Source as a URN
	EventType string `json:"event_type"` // Event type generated by this Source, if applicable
}
